/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStatisticsRouteImport } from './routes/_app.statistics'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPrescriptionsRouteImport } from './routes/_app.prescriptions'
import { Route as AppPharmacyRouteImport } from './routes/_app.pharmacy'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppMyAppointmentsRouteImport } from './routes/_app.my-appointments'
import { Route as AppMedicalHistoryRouteImport } from './routes/_app.medical-history'
import { Route as AppLabReportsRouteImport } from './routes/_app.lab-reports'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConsentsRouteImport } from './routes/_app.consents'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsRoute = AppPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppPharmacyRoute = AppPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAppointmentsRoute = AppMyAppointmentsRouteImport.update({
  id: '/my-appointments',
  path: '/my-appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalHistoryRoute = AppMedicalHistoryRouteImport.update({
  id: '/medical-history',
  path: '/medical-history',
  getParentRoute: () => AppRoute,
} as any)
const AppLabReportsRoute = AppLabReportsRouteImport.update({
  id: '/lab-reports',
  path: '/lab-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsentsRoute = AppConsentsRouteImport.update({
  id: '/consents',
  path: '/consents',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/appointments': typeof AppAppointmentsRoute
  '/audit': typeof AppAuditRoute
  '/consents': typeof AppConsentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/lab-reports': typeof AppLabReportsRoute
  '/medical-history': typeof AppMedicalHistoryRoute
  '/my-appointments': typeof AppMyAppointmentsRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/prescriptions': typeof AppPrescriptionsRoute
  '/profile': typeof AppProfileRoute
  '/statistics': typeof AppStatisticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AppAdminRoute
  '/appointments': typeof AppAppointmentsRoute
  '/audit': typeof AppAuditRoute
  '/consents': typeof AppConsentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/lab-reports': typeof AppLabReportsRoute
  '/medical-history': typeof AppMedicalHistoryRoute
  '/my-appointments': typeof AppMyAppointmentsRoute
  '/patients': typeof AppPatientsRoute
  '/pharmacy': typeof AppPharmacyRoute
  '/prescriptions': typeof AppPrescriptionsRoute
  '/profile': typeof AppProfileRoute
  '/statistics': typeof AppStatisticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/consents': typeof AppConsentsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/lab-reports': typeof AppLabReportsRoute
  '/_app/medical-history': typeof AppMedicalHistoryRoute
  '/_app/my-appointments': typeof AppMyAppointmentsRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/pharmacy': typeof AppPharmacyRoute
  '/_app/prescriptions': typeof AppPrescriptionsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/statistics': typeof AppStatisticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/admin'
    | '/appointments'
    | '/audit'
    | '/consents'
    | '/dashboard'
    | '/lab-reports'
    | '/medical-history'
    | '/my-appointments'
    | '/patients'
    | '/pharmacy'
    | '/prescriptions'
    | '/profile'
    | '/statistics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/admin'
    | '/appointments'
    | '/audit'
    | '/consents'
    | '/dashboard'
    | '/lab-reports'
    | '/medical-history'
    | '/my-appointments'
    | '/patients'
    | '/pharmacy'
    | '/prescriptions'
    | '/profile'
    | '/statistics'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/sitemap.xml'
    | '/_app/admin'
    | '/_app/appointments'
    | '/_app/audit'
    | '/_app/consents'
    | '/_app/dashboard'
    | '/_app/lab-reports'
    | '/_app/medical-history'
    | '/_app/my-appointments'
    | '/_app/patients'
    | '/_app/pharmacy'
    | '/_app/prescriptions'
    | '/_app/profile'
    | '/_app/statistics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/statistics': {
      id: '/_app/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prescriptions': {
      id: '/_app/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pharmacy': {
      id: '/_app/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-appointments': {
      id: '/_app/my-appointments'
      path: '/my-appointments'
      fullPath: '/my-appointments'
      preLoaderRoute: typeof AppMyAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical-history': {
      id: '/_app/medical-history'
      path: '/medical-history'
      fullPath: '/medical-history'
      preLoaderRoute: typeof AppMedicalHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab-reports': {
      id: '/_app/lab-reports'
      path: '/lab-reports'
      fullPath: '/lab-reports'
      preLoaderRoute: typeof AppLabReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consents': {
      id: '/_app/consents'
      path: '/consents'
      fullPath: '/consents'
      preLoaderRoute: typeof AppConsentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppConsentsRoute: typeof AppConsentsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLabReportsRoute: typeof AppLabReportsRoute
  AppMedicalHistoryRoute: typeof AppMedicalHistoryRoute
  AppMyAppointmentsRoute: typeof AppMyAppointmentsRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPharmacyRoute: typeof AppPharmacyRoute
  AppPrescriptionsRoute: typeof AppPrescriptionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStatisticsRoute: typeof AppStatisticsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppAuditRoute: AppAuditRoute,
  AppConsentsRoute: AppConsentsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLabReportsRoute: AppLabReportsRoute,
  AppMedicalHistoryRoute: AppMedicalHistoryRoute,
  AppMyAppointmentsRoute: AppMyAppointmentsRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPharmacyRoute: AppPharmacyRoute,
  AppPrescriptionsRoute: AppPrescriptionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppStatisticsRoute: AppStatisticsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
